name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b796091e6a988a4930d49da3a8e8c6b45efedcb1b696a289fc1a2bb1f4115582"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
unsup = "1.2.7"
