name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b11d1130272a13014dc780296802c537e8565f63af4df07066ba72e88db12a57"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
unsup = "1.2.7"
