name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e9d94cfe38130ba3f5ec9e45a965d1ce2d6e0837efc28ba04737904ce78522"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
unsup = "1.2.7"
