[flavor_groups.xaero]
name = "Xaero 系列"
side = "client"

[[flavor_groups.xaero.choices]]
id = "xaero_none"
name = "无"
description = "不安装 Xaero 系列 Mod。"

[[flavor_groups.xaero.choices]]
id = "xaero_minimap"
name = "小地图"
description = "只安装 Xaero 的小地图。"

[[flavor_groups.xaero.choices]]
id = "xaero_worldmap"
name = "World Map"
description = "只安装 Xaero 的世界地图。"

[[flavor_groups.xaero.choices]]
id = "xaero_plus"
name = "XaeroPlus"
description = "安装 Xaero 的小地图、Xaero 的世界地图和 XaeroPlus。"

[[flavor_groups.xaero.choices]]
id = "xaero_maplink"
name = "Map Link"
description = "安装 Xaero 的小地图、Xaero 的世界地图和 Map Link。"

[[flavor_groups.xaero.choices]]
id = "xaero_all"
name = "All"
description = "安装 Xaero 的小地图、Xaero 的世界地图、XaeroPlus 和 Map Link。"

[metafile.xaeros-minimap]
flavors = ["xaero_minimap", "xaero_plus", "xaero_maplink", "xaero_all"]

[metafile.xaeros-world-map]
flavors = ["xaero_worldmap", "xaero_plus", "xaero_maplink", "xaero_all"]

[metafile.xaeroplus]
flavors = ["xaero_plus", "xaero_all"]

[metafile.maplink]
flavors = ["xaero_maplink", "xaero_all"]