name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81d22267374613a79d4517699b16019c2be4ebe7fbbceb9bc51cf968f6acf778"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
unsup = "1.2.7"
