name = "Slideshow Proxy"
filename = "slideshowproxy-1.0.4+mc1.20.4.jar"
side = "client"

[download]
url = "https://gitea.dusays.com/fenychn0206/static/raw/branch/main/slideshowproxy-1.0.4+mc1.20.4.jar"
hash-format = "sha256"
hash = "8ebbe875c660b422e6dace3f5c1c55918e1faf8bc5c64015c51e72ab26b50542"

[option]
optional = true
description = "[[ 由社区提供 ]]\n在没有代理的情况下加速部分 Slideshow 图片的显示。"
default = true